
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8853492A92E1D913DFA5B3BA8D251F11'
    
_lr_action_items = {'DECREMENT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[1,-4,-3,1,-7,-5,1,-6,-8,-9,-1,1,-2,-10,]),'READ':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[8,-4,-3,8,-7,-5,8,-6,-8,-9,-1,8,-2,-10,]),'OPEN_LOOP':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[3,-4,-3,3,-7,-5,3,-6,-8,-9,-1,3,-2,-10,]),'WRITE':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[4,-4,-3,4,-7,-5,4,-6,-8,-9,-1,4,-2,-10,]),'GO_LEFT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[5,-4,-3,5,-7,-5,5,-6,-8,-9,-1,5,-2,-10,]),'INCREMENT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[2,-4,-3,2,-7,-5,2,-6,-8,-9,-1,2,-2,-10,]),'GO_RIGHT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[7,-4,-3,7,-7,-5,7,-6,-8,-9,-1,7,-2,-10,]),'CLOSE_LOOP':([1,2,4,5,7,8,9,10,11,12,13,],[-4,-3,-7,-5,-6,-8,-9,-1,13,-2,-10,]),'$end':([1,2,4,5,6,7,8,9,10,12,13,],[-4,-3,-7,-5,0,-6,-8,-9,-1,-2,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'commands':([0,3,],[6,11,]),'loop':([0,3,6,11,],[9,9,9,9,]),'command':([0,3,6,11,],[10,10,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commands","S'",1,None,None,None),
  ('commands -> command','commands',1,'p_commands','brainfuck_interpreter.py',60),
  ('commands -> commands command','commands',2,'p_commands','brainfuck_interpreter.py',61),
  ('command -> INCREMENT','command',1,'p_command','brainfuck_interpreter.py',77),
  ('command -> DECREMENT','command',1,'p_command','brainfuck_interpreter.py',78),
  ('command -> GO_LEFT','command',1,'p_command','brainfuck_interpreter.py',79),
  ('command -> GO_RIGHT','command',1,'p_command','brainfuck_interpreter.py',80),
  ('command -> WRITE','command',1,'p_command','brainfuck_interpreter.py',81),
  ('command -> READ','command',1,'p_command','brainfuck_interpreter.py',82),
  ('command -> loop','command',1,'p_command','brainfuck_interpreter.py',83),
  ('loop -> OPEN_LOOP commands CLOSE_LOOP','loop',3,'p_loop','brainfuck_interpreter.py',93),
]
